"""add auto_reprocessed and reprocess_reason to jobs

Revision ID: 1c5841080ea0
Revises: 8126ef07d529
Create Date: 2026-04-01 15:30:06.176379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5841080ea0'
down_revision: Union[str, None] = '8126ef07d529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('auto_reprocessed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('jobs', sa.Column('reprocess_reason', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'reprocess_reason')
    op.drop_column('jobs', 'auto_reprocessed')
    # ### end Alembic commands ###
