"""add use_hybrid to jobs

Revision ID: 8126ef07d529
Revises: b3446bd92fa2
Create Date: 2026-03-25 17:45:54.914367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8126ef07d529'
down_revision: Union[str, None] = 'b3446bd92fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('use_hybrid', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'use_hybrid')
    # ### end Alembic commands ###
